### ISSUE TITLE
will deleting the app clean the keyChain stored data?

### ISSUE THREAD

**Issue by liuxuan30** [kishikawakatsumi/KeychainAccess#188]
Sorry I have to ask a newbie question, but I cannot find a good answer. Will deleting the app clean the keyChain stored data?

**Comment by kishikawakatsumi** [comment]
You cannot it automatically. Because we have no any trigger the app uninstalling.

Things like similar can be achieved by combining the value disappear uninstall such as NSUserDefaults.

For example, you can generate key value when app launching, then store the value to NSUserDefaults. You always to use the value to store keychain as a key.
If app will be uninstalled, the key will be also removed. So you cannot retrieve the value when app installed again.

**Comment by liuxuan30** [comment]
but the value saved in key chain is still there, right?
Another question, can user delete it manually? Thanks

**Comment by kishikawakatsumi** [comment]
> but the value saved in key chain is still there, right?

Yes. The value saved in key chain is still there.

> Another question, can user delete it manually? Thanks

You mean the user can delete any keychain items manually use keychain manager app, like OS X?
If so, no. The users cannot manage/see any keychain items in the iPhone.

**Comment by liuxuan30** [comment]
Thanks! yes, I want to ask is there a way to clean keychain items by user, or by code.
Seems using keychain to save some tokens is not a good idea.
