### ISSUE TITLE
Keep getting errors while saving data to Keychain

### ISSUE THREAD

**Issue by RyanKim01** [kishikawakatsumi/KeychainAccess#199]
```
 keychain["\(PartConfigurationViewController.formName)_all_fields"] = "\(self.dataSource.requiredFields.count)"
        
        keychain["\(PartConfigurationViewController.formName)_invalid_fields"] = String(self.dataSource.invalidFields.count)
```
Whenever I run these methods, I get two errors saying same thing: 

> error:[-67594] failed to convert data to string

Can you guess why this is causing a problem?? self.dataSource.invalidFields.count is just Int type, btw.

**Comment by kishikawakatsumi** [comment]
> error:[-67594] failed to convert data to string

@RyanKim01 Are you sure that error occurred at those lines? Because it occurs only in `getString(key: String)`. Not in any `set` methods.

Could you check whether invoking Keychain's `set` method in `PartConfigurationViewController.formName` or `self.dataSource.requiredFields.count`?

**Comment by RyanKim01** [comment]
@kishikawakatsumi 
I did go through my code and sure thing that wasn't a problem as you mentioned.
Problem is occurring at below code:
```
let keys = keychain.allKeys()
        for key in keys {
            dictionary["\(key)"] = keychain["\(key)"]
        }
```
I'm basically iterating through keychain to save (key, value) pair to dictionary. Would love to know what is causing a problem.

**Comment by kishikawakatsumi** [comment]
@RyanKim01 Sorry for the late response.

I believe your keychain stores non-string binary data. `keychain[key]` always returns `String` value. So if the keychain stores binary data, the data cannot be converted to `String`, then returns `nil`.
That's why the error was occurred.

So you should receive the value as `NSData` first, then try to convert `String`. If conversion is succeeded, store the string to the dictionary. If failed, store the data as `NSData`. Like the following:

```swift
for key in keychain.allKeys() {
    let data = keychain[data: key]!
    if let string = String(data: data, encoding: NSUTF8StringEncoding) {
        dictionary[key] = string
    } else {
        dictionary[key] = data
    }
}
```
