### ISSUE TITLE
Handle Cancel button clicked when Updating a Touch ID protected item

### ISSUE THREAD

**Issue by KeIMG** [kishikawakatsumi/KeychainAccess#338]
How to handle the situation when Cancel button has been clicked when Updating a Touch ID protected item?

**Comment by kishikawakatsumi** [comment]
@KeIMG You can achieve it by catching `Status.userCanceled` error, like the following.

```
do {
    try keychain
        .accessibility(.whenPasscodeSetThisDeviceOnly, authenticationPolicy: .userPresence)
        .set("...", key: "..")
} catch (Status.userCanceled) {
    // A user canceled the touch ID prompt
} catch {
    // Other errors
}
``

**Comment by KeIMG** [comment]
Great, found that enum 👍

**Comment by Ontokrat** [comment]
Hello,

I can't manage to catch if a user canceled the touch ID / password prompt => the key is always returned, as `nil` if the user canceled the prompt. 

That's a major issue because if the key is `nil`, I (later in the code) assume there is none and so I create it:
=> so in fact I modify it => meaning basically if the user cancel the prompt, its key is updated....

I'm working on a `MacOS` app.

Any idea? Thanks.

```swift
func findKeychainKey(identifier: String) throws -> Data? {
    let keychain = Keychain(service: "XXXX", accessGroup: "XXXX")
    do {
        let findKey = try keychain.getData(identifier)
        return findKey!
    } catch (Status.userCanceled) {
        // A user canceled the touch ID / password prompt
        print("The user canceled the touch ID / password prompt.")
        throw KeychainError.userCancelled
    } catch let error {
        print("error: \(error)")
        throw KeychainError.emptyKey
    }
}
