### ISSUE TITLE
Not support init Keychain with protocolType and accessGroup?

### ISSUE THREAD

**Issue by wigl** [kishikawakatsumi/KeychainAccess#356]
Init Keychain like:
`Keychain.init(server: "https://www.github.com", protocolType: .https, accessGroup: "12ABCD3E4F.shared)`
Now I can't use parameter `accessGroup`,it will use default accessGroup(bundleID or keychain groups),not support custom set accessGroup.
Some Reason?
thank you!

**Comment by kishikawakatsumi** [comment]
@wigl In the Keychain API, the `kSecAttrAccessGroup` attribute is valid when `kSecClassGenericPassword` is specified. If `kSecClassInternetPassword` is specified (using the initializer that takes `server` argument), `kSecClassGenericPassword` is just ignored by Keychain API. Therefore, this library does not support specifying `accessGroup` in the initializer that takes `server` argument. Because it makes no sense to specify it. Does it answer for you?

**Comment by kishikawakatsumi** [comment]
Closing due to no response

**Comment by yangyubo** [comment]
@kishikawakatsumi after a slight modification on KeychainAccess, I'm able to create an internet password item with `kSecAttrAccessGroup` and `kSecAttrSynchronizable` attributes enabled, I can confirm that `kSecClassInternetPassword` can work with `kSecAttrAccessGroup`, at least on macOS.

And, as [stated in official document](https://developer.apple.com/documentation/security/ksecclassinternetpassword), it should also works on iOS.

Am I missing anything on this issue? Is it proper to submit a PR?

**Comment by jeff-h** [comment]
@yangyubo I'm struggling with the configuration needed for keychain sharing to work... I just can't get it happening :( Any chance you'd have a quick look at my demo apps and see if you can spot anything obvious? https://github.com/jeff-h/sharedKeychainAccessDemo
