### ISSUE TITLE
**Cannot convert value of type '[NSObject : Any]' to expected argument type '[String : Any]?'** 

### ISSUE THREAD

**Issue by rizwan95** [kishikawakatsumi/KeychainAccess#369]
I am getting this error 

> **Cannot convert value of type '[NSObject : Any]' to expected argument type '[String : Any]?'** 

when I try to use KeyChainAccess framework.

The line where it occurs is return `NSError(domain: domain, code: code, userInfo: userInfo)`

Here is the complete method. 

`extension CFError {
    var error: NSError {
        let domain = CFErrorGetDomain(self) as String
        let code = CFErrorGetCode(self)
        let userInfo = CFErrorCopyUserInfo(self) as! [NSObject: Any]

        return NSError(domain: domain, code: code, userInfo: userInfo)
    }
}`

**Comment by kishikawakatsumi** [comment]
@rizwan95 Can you share a reproducible sample project?

**Comment by hudaniel** [comment]
Having the same issue. I just trying to pod install SoundCloud SDK, maybe they're using an old version.

https://www.dropbox.com/s/uxacez2mbdhwrpg/CloudPlayer.zip?dl=0

Empty project with just some installed cocoapods.

**Comment by kishikawakatsumi** [comment]
@hudaniel This is due to fix for Swift 4 https://github.com/kishikawakatsumi/KeychainAccess/commit/ed628ded567c63efab9a0ef94d294e96da6c5fdb#diff-f86e593150068fc1ce31cf1ba415c133

1. file an issue to update SoundcloudSDK to support Swift 4 https://github.com/delannoyk/SoundcloudSDK
2. use Swift 3 until SoundcloudSDK supports Swift 4
