### ISSUE TITLE
Recommended way to store and obtain numeric values and Bool flags?

### ISSUE THREAD

**Issue by mr746866** [kishikawakatsumi/KeychainAccess#385]
Sorry if this has been answered somewhere else.

I need to store numeric values (`Int`, `Double`, `Float`) and `Bool` flags to the keychain. 

I can just save them as `String`s and parse them to obtain the respective values, but I was wondering if there is a better way.

**Comment by kishikawakatsumi** [comment]
@mr746866 
Keychain API only accepts NSData. This library provides a utility method that accepts String parameters because String is commonly used. Therefore, to save values ​​other than NSData, you need to implement conversion between NSData yourself.

The easy way is converting to String, like `true <=> "true"`, `123 <=> "123"` etc.
