### ISSUE TITLE
WatchOS cannot create a Keychain Object

### ISSUE THREAD

**Issue by tommycarpi** [kishikawakatsumi/KeychainAccess#388]
On WatchOS I'm trying to read some value from the shared iCloud Keychain.
Under **Capabilities** of **Watch Extensions** I've already enabled **Keychain Sharing**, setting the same **Keychain Groups** as the iOS app.

The problem is that I cannot create a Keychin object on WatchOS. This is the code

`let keychain = Keychain(service: Constants.keychainID).synchronizable(true)`

which returns an empty list `[]`.

What am I missing?

**Comment by kishikawakatsumi** [comment]
@tommycarpi You misuse the API. You just configure keychain parameters. To store value, you should invoke `set()` method. Please read usage section . https://github.com/kishikawakatsumi/KeychainAccess#book-usage

**Comment by RobSwish** [comment]
Did you fix this? I'm having the exact same issue I think. I believe I am setting the data correctly.

I need to set the data in my iPhone app and read it in my Apple Watch app. 

I can confirm that the data is being saved within the iPhone app, but when I try and read the data on my Apple Watch keychain = [].

I'd really appreciate the help, I've been sat here for 2 hours now trying to work out why the Apple Watch isn't getting the data.

Thank you.

**Comment by tommycarpi** [comment]
@RobSwish no I gave up because I could not make it work unfortunately. I'm sorry

**Comment by RobSwish** [comment]
Thanks for the reply 🙂, in the end I had to assume that this is because Apple does not allow Keychain sharing between the phone and the watch. Instead you should pass data to the watch via WatchConnectivity and then you can save it in the watch's keychain.

I think the creator of this repo should add a quick line about this in the sharing section, I think this has caused a few people some issues trying to work it out. @kishikawakatsumi? Something like: "Apple does not allow sharing of Keychain items between the phone and watch, you need to use WatchConnectivity". I believe this change came in after WatchOS2 or something.

As you can technically access the keychain shared group in the watch it appears to be working, when in fact the item for key is always nil unless you set the item on the watch itself.

This all feels like Apple plans to connect the two again one day, I don't understand why they would allow you to add the Keychain Sharing capability if you can't use it, unless it's still there for those of us that still support apps running on WatchOS2?

Great repo though,  thanks a lot! It made storing the data very easy, I just wish I knew what I know now before the 4 hours of trial and error. 😂

**Comment by sadanandhexalitcs** [comment]
Try this @tommycarpi @RobSwish  
in iPhone
let keychain = Keychain(service: Constants.keychainID, accessGroup: "123.Shared").synchronizable(true)
keychain[string: "ABC"] = "abc"

in Watch
let keychain = Keychain(service: Constants.keychainID, accessGroup: "123.Shared")
let value = keychain[string: "ABC"]

//Output "abc"
