### ISSUE TITLE
XCode 10 issue "Required entitlement isn't present"

### ISSUE THREAD

**Issue by martiwi** [kishikawakatsumi/KeychainAccess#399]
I have unit test which are using KeychainAccess library.

The issue is that with latest XCode version (Version 10.0 (10A255)) it is not working, I have the following error message back:

> Internal error when a required entitlement isn't present, client has neither application-identifier nor keychain-access-groups entitlements.

But, when using the beta version : (Version 10.0 beta 2 (10L177m)) it is working fine.

**Comment by robertying** [comment]
I found one possible solution which works for me.

1. Go to your project settings
1. Select `Capabilities` tab
1. Locate `Keychain sharing`
1. Enable it

You should be able to use `KeychainAccess` now.

**Comment by eMdOS** [comment]
> I found one possible solution which works for me.
> 
> 1. Go to your project settings
> 2. Select `Capabilities` tab
> 3. Locate `Keychain sharing`
> 4. Enable it
> 
> You should be able to use `KeychainAccess` now.

It doesn't.

I just tested it in Xcode 10.2.

I have a couple of question:

1. If `Keychain Sharing` is for sharing only, why it needs to be enabled? If only adding/removing it shouldn't be necessary, isn't it?

2. What about when KeychainAccess fails in a Unit Test target?. `Keychain Sharing` option is for Application Targets only.

**Comment by woolie** [comment]
You need a TestHost to run your unit tests in. You can add keychain sharing to your test host.

**Comment by crspybits** [comment]
For a Swift package manager based project, for iOS, any ideas how to run unit tests and not run into this Capabilities issue? I'm making a derived library package and have unit tests I want to run. So far I can only run them in the Cocoapods version of the package.

**Comment by kishikawakatsumi** [comment]
Use test host app, and add Keychain.entitlements to the test host app.

**Comment by levibostian** [comment]
Leaving this for future visitors: 

When I read the comments above saying to use a test host app, I was not sure what that meant. I assumed it meant move my unit tests to the UI tests target as those tests run inside of an application. After further searching, I found out you need to simply enable the host app for your unit tests target. Here is a tip on how to do that. 

1. Go into settings for the xcode test target and enable the host app. 

![2020-02-12 at 2 43 PM](https://user-images.githubusercontent.com/2041082/74375921-d7e15480-4da6-11ea-853d-d893169815ca.png)

2. This is all you need to do. But you might have some issues when running unit tests now because the code in `AppDelegate` are going to execute now when they may not have previously. To block `AppDelegate` code from running when you run *unit* tests:

![2020-02-12 at 2 45 PM](https://user-images.githubusercontent.com/2041082/74376066-14ad4b80-4da7-11ea-93e0-16f8c6f97f32.png)
![2020-02-12 at 2 45 PM2](https://user-images.githubusercontent.com/2041082/74376067-16770f00-4da7-11ea-95ab-81f4a5531f47.png)

**Comment by AbbyJanke** [comment]
Just wanted to give it a mention that I had no issues with the error on iOS and iPadOS but when I tried to use Mac Catalyst I received this error.
