### ISSUE TITLE
iOS Example does not work on iOS 13

### ISSUE THREAD

**Issue by ehmjaysee** [kishikawakatsumi/KeychainAccess#446]
The main view (AccountsViewController) is always blank run running on iOS 13. Adding new items seems to work and there are no errors, but the main view controller is always blank.

**Comment by lukas1** [comment]
when you restart the app, stored items will be displayed

**Comment by kishikawakatsumi** [comment]
@ehmjaysee Thank you for reporting. In iOS 13, it changes a modal view's behavior (Sheet style transition). If the input view is presented modally with the sheet style transition, `viewWillAppear:` isn't called when it dismissed. That's why the main view doesn't reload.

Fixed by 5e16d0e5b26fb3c75d4a23ba943b562d4919d50a
