### ISSUE TITLE
Carthage support only works on "master", not "v1.2.0" tag

### ISSUE THREAD

**Issue by siemensikkema** [kishikawakatsumi/KeychainAccess#64]
ie. using the line `github "kishikawakatsumi/KeychainAccess"` doesn't work but `github "kishikawakatsumi/KeychainAccess" "master"` in the Cartfile does.
I'm using Carthage 0.6.5 and Xcode 6.3.1.

**Comment by kishikawakatsumi** [comment]
I had uploaded pre-built binary for some major releases in last week. (See https://github.com/kishikawakatsumi/KeychainAccess/releases) If you're saying is that it is just downloaded but it will not be build. It's correct behavior.

Carthage skip build phase if it found pre-built binary for the tag you specified. That's why it will be built only when specify "master" because there are not pre-built binary for "master".

If you do not want to use pre-built binary (want to always build from source), you can use `--no-use-binaries` option with carthage command. Like this: `carthage update --no-use-binaries`.  I hope that answers your question?

**Comment by siemensikkema** [comment]
yup, that's exactly what happened. My bad! Thanks very much for the detailed reply!
